import Head from 'next/head'
import HistoryList from '../components/HistoryList'
import SearchBar from '../components/SearchBar'



export default function Home() {
  return (
    <div className="dark:bg-gray-900 bg-slate-300  h-screen">
      <Head>
        <title>Nasa Ai Search Engine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>


<div className="mt-[6%]   flex justify-center ">
  <SearchBar/>
</div>
<HistoryList/>



    </div>
  )

}
