import React, { useRef } from 'react'
import SearchEle from '../components/SearchEle' 
import { useRouter } from 'next/router';
import  Head  from 'next/head';
import Lottie from "lottie-react";

import groovyWalkAnimation from "../public/Images/nasa.json";
function Search() {
  let router= useRouter();
  const  pid  = router.asPath;
   let val = pid.slice(router.asPath.indexOf("?=")+2); 
   const lottieRef = useRef();

   function hoverevent(){
    lottieRef.current.setSpeed(7)
   }
   function hovereventends(){
    lottieRef.current.setSpeed(1)

   }

   return (
    <div className="text-white">
      <Head>
          <title>Nasa Ai Search Engine</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/ico/nasa.png" />
          
        </Head>


        <main>
          <div className="fixed w-full pb-2 bg-gray-700/20 h-16 md:h-24 backdrop-blur-md"><div className='h-full  md:flex max-w-4xl w-[90%] justify-center  flex mt-1  md:mx-0  mx-auto '>
          <div className='lg:ml-12 w-[80px]  md:w-[100px]  cursor-pointer scale-90 hover:opacity-95 '>      
      <Lottie
      onMouseOver={hoverevent}
      onMouseLeave={hovereventends}
          
            lottieRef={lottieRef}
             animationData={groovyWalkAnimation} 
             />
      </div>
       <div className="w-full mt-2 md:mt-5"> <SearchEle inputDafultVal={val}  /></div>
        </div></div>
       

        
        </main>
        <div className="pt-[70px] md:pt-[100px]">
       {val}
       </div>      
    </div>
  )
}

export default Search